# Generated by Django 4.0.3 on 2022-04-03 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('sex', models.IntegerField(choices=[(0, 'female'), (1, 'male')])),
                ('year_of_birth', models.IntegerField(null=True)),
            ],
        ),
    ]
