# Generated by Django 4.0.3 on 2022-04-04 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0002_staff_alter_members_sex_trainings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='year_of_birth',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('capacity', models.SmallIntegerField()),
                ('training', models.ManyToManyField(to='gym_app.trainings')),
            ],
        ),
    ]
