# Generated by Django 4.0.3 on 2022-04-06 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0004_trainings_date_trainings_end_time_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Room',
            new_name='Rooms',
        ),
        migrations.AddField(
            model_name='members',
            name='password',
            field=models.CharField(default='Asd123!', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='members',
            name='username',
            field=models.CharField(default='user1', max_length=64),
            preserve_default=False,
        ),
    ]
