# Generated by Django 4.0.3 on 2022-04-06 18:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gym_app', '0005_rename_room_rooms_members_password_members_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
