# Generated by Django 4.0.3 on 2022-04-09 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0009_alter_trainings_trainer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='training',
        ),
        migrations.AddField(
            model_name='rooms',
            name='training',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='gym_app.trainings'),
        ),
    ]
