# Generated by Django 4.0.3 on 2022-04-10 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0010_remove_rooms_training_rooms_training'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='type',
            field=models.CharField(choices=[(1, 'Recepctionist'), (2, 'Director'), (3, 'Accountant')], max_length=64),
        ),
    ]
