# Generated by Django 4.0.3 on 2022-04-13 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0011_alter_staff_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainings',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trainings',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym_app.trainers'),
        ),
    ]
