# Generated by Django 4.0.3 on 2022-04-13 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_app', '0012_trainings_id_alter_trainings_trainer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainings',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
